export const COLOR = {
  PRIMARY: '#7E85F9',
  SECONDARY: '#75BFCF',
  WARNING: '#FE6C6B',
  SECONDARY_TINT: '#F2F8FA',
  LIGHT_BACKGROUND: '#FFFFFF',
  DARK_BACKGROUND: '#07152C',

  DARK_TINT_LINE: '#142B50',
  DARK_TINT: '#0C2040',
  LIGHT_TINT_LINE: '#F2F8FA',
  LIGHT_TINT: '#FCFCFC',
};

export const TEXT_COLOR = {
  LIGHT_PRIMARY: '#031637',
  LIGHT_SECONDARY: '#8A8E9C',
  DARK_PRIMARY: '#ffffff',
  DARK_SECONDARY: '#8A8E9C',
};
